create table public.stylists (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  name text not null,
  title text,
  phone text,
  email text,
  avatar_url text
);

alter table public.stylists disable row level security;
