-- 1. 建立 messages 資料表
create table public.messages (
  id bigint generated by default as identity primary key,
  content text not null,
  sender_id text not null, -- LINE User ID 或 'ADMIN'
  receiver_id text not null, -- LINE User ID 或 'ADMIN'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 為了方便開發，暫時關閉 RLS (Row Level Security)
-- 注意：正式上線建議開啟 RLS 並設定適當的 Policy
alter table public.messages disable row level security;

-- 2. 開啟 Realtime 監聽
-- 將 messages 表加入 supabase_realtime publication
-- 這樣前端 (LIFF/Web) 才能透過 supabase.channel 監聽此表的變動 (INSERT/UPDATE/DELETE)
alter publication supabase_realtime add table messages;
