create table public.salon_info (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  email text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default row
insert into public.salon_info (name, address, email, image_url)
values ('極致美學沙龍會館 (Central Plaza)', '台北市信義區忠孝東路五段 123 號 4 樓', 'contact@beauty-salon-pro.com', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCJMRVTW3ayRoqi5ZrDNrEovFo4AVMQISSN6ZuWwe6xw6hmS5YEIONmzOH1ncr7i7dDh_iof0v5X5WRcjuAN0tMFCavA2vcoYmndBrj6yLTM3jsKYa55-tO8FZPZixCPREULF2nKLCRRCzUHnXkWI9ryQ2srqn7bKRW0JZiX3UGRbJv1cMuBZ9te1hbe5pV8WZrfHsTiYNWgXiuomEkBZFztSsYWc3t7v2mtaez-GPYMsaGB1Rhq8nvJQuNYlDcPyaiNnEmySerDk-d');

-- Enable RLS
alter table public.salon_info enable row level security;

-- Create policy to allow read access to everyone
create policy "Enable read access for all users" on public.salon_info for select using (true);

-- Create policy to allow update access for all users (simplistic for this demo environment)
create policy "Enable update access for all users" on public.salon_info for update using (true);
create policy "Enable insert access for all users" on public.salon_info for insert with check (true);
