-- 建立 bookings 資料表
create table public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id text not null,
  message text not null,
  raw_event jsonb
);

-- 為了方便測試，暫時關閉 RLS (Row Level Security)
-- 這樣您的 API 就可以順利寫入資料，不會被權限擋住
alter table public.bookings disable row level security;
